server:
  port: 8080
  tomcat:
    threads:
      max: 10
      min-spare: 2

spring:
  servlet:
    multipart:
      file-size-threshold: 0B
      max-file-size: 500MB
      max-request-size: 500MB
      location: /tmp
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge?currentSchema=document_schema
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000

minio:
  url: ${STORAGE_URL}
  public-url: ${STORAGE_PUBLIC_URL:}
  access-key: ${STORAGE_ACCESS_KEY}
  secret-key: ${STORAGE_SECRET_KEY}
  bucket-name: ${STORAGE_BUCKET:document-bucket}
  download-ttl: ${MINIO_DOWNLOAD_TTL:15}
  upload-ttl: ${MINIO_UPLOAD_TTL:40}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html