# Server Configuration
spring.application.name=document-management-service
server.port=8080
server.servlet.context-path=/documents-manager

# Database Configuration
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=${POSTGRES_SCHEMA}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MinIO Configuration
minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}
minio.url-expiry-time=${MINIO_URL_EXPIRY_TIME}
minio.external.endpoint=${MINIO_EXTERNAL_ENDPOINT}

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=520MB

# Memory settings for handling large files
spring.servlet.multipart.resolve-lazily=true

#delegate MaxUploadSizeExceededException to custom handler
server.tomcat.max-swallow-size=-1
spring.mvc.throw-exception-if-no-handler-found=true

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.docmanagement=DEBUG

# Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-support-form-data=true
springdoc.override-with-generic-response=false
springdoc.model-converters.pageable-converter.enabled=false
springdoc.disable-kotlin-support=true
