server:
  tomcat:
    threads:
      max: 50
      min-spare: 10

spring:
  config:
    import: optional:file:.env[.properties]

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    name: document-management-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
    build:
      enabled: true

  security:
    enabled: false

minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:2DmLGeZ.}
  bucket-name: documents

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

info:
  app:
    name: document-management-service
    description: API for managing PDF documents
    version: 0.0.1-SNAPSHOT

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

deploy:
  resources:
    limits:
      memory: 256M
environment:
  JAVA_TOOL_OPTIONS: -Xmx128m -Xms64m
