# PostgreSQL DataBase Configuration
spring.datasource.url=${POSTGRESQL_HOST}${POSTGRESQL_DATABASE}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Minio Configuration
minio.endpoint=${MINIO_PORT_HOST}
minio.port-api=${MINIO_PORT_API}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.secure=${MINIO_ROOT_PASSWORD}
minio.bucket-name=${MINIO_BUCKET_NAME}
minio.file-size=${MINIO_FILE_SIZE}
