# Server Configuration
spring.application.name=document-management-service
server.port=8080
server.servlet.context-path=/documents-manager

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=clara_bd_user
spring.datasource.password=clara_bd_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MinIO Configuration
minio.endpoint=http://localhost:9000
minio.access-key=clara_minio_user
minio.secret-key=clara_minio_password
minio.bucket-name=documents
minio.url-expiry-time=30

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=520MB

# Memory settings for handling large files
spring.servlet.multipart.resolve-lazily=true

#delegate MaxUploadSizeExceededException to custom handler
server.tomcat.max-swallow-size=-1
spring.mvc.throw-exception-if-no-handler-found=true

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.com.docmanagement=DEBUG

# Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-support-form-data=true
springdoc.override-with-generic-response=false
springdoc.model-converters.pageable-converter.enabled=false
springdoc.disable-kotlin-support=true
