# Server Configuration
server.servlet.contextPath=/
server.port=8080

# Context path swagger-ui
springdoc.swagger-ui.path=/swagger-ui.html

# PostgreSQL DataBase Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# Server error Configuration
server.error.include-message=always
server.error.include-stacktrace=never
