# PostgreSQL DataBase Configuration
spring.datasource.url=${POSTGRESQL_HOST}${POSTGRESQL_DATABASE}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Minio Configuration
minio.endpoint=${MINIO_PORT_HOST}
minio.port-api=${MINIO_PORT_API}
minio.root-user=${MINIO_ROOT_USER}
minio.root-password=${MINIO_ROOT_PASSWORD}
minio.secure=${MINIO_SECURE}
minio.bucket-name=${MINIO_BUCKET_NAME}
minio.file-size=${MINIO_FILE_SIZE}
