services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME={POSTGRES_USER}
      - POSTGRESQL_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE={DATABASE_NAME}
      - POSTGRESQL_POSTGRES_PASSWORD={POSTGRES_ADMIN_PASSWORD} # Password of user "postgres"
  localstack:
    container_name: localstack-container
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=ssm
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG:-0}
    volumes:
      - challenge_localstack_data:/var/lib/localstack
      - ./init-scripts:/etc/localstack/init
      - ./init-scripts:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_localstack_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
