services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:15.4.0
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD} # Password of user "postgres"
  minio:
    image: minio/minio:latest
    container_name: minio_container
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    networks:
      - batch_network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
  # Include all the necessary settings to include a document management service in the stack
  # Remember to configure this service to limit the memory to 50MB
  document-management-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: document-management-service_container
    ports:
      - "8080:8080"
    networks:
      - batch_network
    depends_on:
      - minio
      - postgresql
    environment:
      - JAVA_OPTS=-Xmx50m -Xms50m
      - SPRING_DATASOURCE_URL=${POSTGRESQL_HOST}${POSTGRESQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT_API=${MINIO_PORT_API}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_FILE_SIZE=${MINIO_FILE_SIZE}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - challenge_document-management-service_data:/data

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local
  challenge_document-management-service_data:
    driver: local
networks:
  batch_network:
    driver: bridge
